### PR TITLE
Add Travis infrastructure

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by untitaker** [comment]
This runs the tests whenever you commit something new to master, see https://travis-ci.org/

You still need to enable the repo on that site.

**Comment by untitaker** [comment]
The reason I've submitted is that there's a Python 3 imcompatibility with your library (for which I will submit a separate patch).

**Comment by untitaker** [comment]
Also the tests fail, there actually seems to be a bug in `ansi` regarding background vs. foreground colors?

    _____________________________________________________ test_fg_bg ______________________________________________________

        def test_fg_bg():
            from ansi.colour import fg, bg
            from ansi.colour.fx import reset
            msg = (bg.red, fg.yellow, 'Hello world!', reset)
    >       assert ''.join(map(str, msg)) == '\x1b[41m\x1b[1;33mHello world!\x1b[0m'
    E       assert '\x1b[41m\x1b...world!\x1b[0m' == '\x1b[41m\x1b[...world!\x1b[0m'
    E         - \x1b[41m\x1b[33mHello world!\x1b[0m
    E         + \x1b[41m\x1b[1;33mHello world!\x1b[0m
    E         ?              ++

    test_ansi.py:16: AssertionError
    _____________________________________________________ test_sugar ______________________________________________________

        def test_sugar():
            from ansi.colour import fg, bg
    >       assert bg.red(fg.yellow('Hello world!')) == \
                '\x1b[41m\x1b[1;33mHello world!\x1b[0m\x1b[0m'
    E       assert '\x1b[41m\x1b...x1b[0m\x1b[0m' == '\x1b[41m\x1b[...x1b[0m\x1b[0m'
    E         - \x1b[41m\x1b[33mHello world!\x1b[0m\x1b[0m
    E         + \x1b[41m\x1b[1;33mHello world!\x1b[0m\x1b[0m
    E         ?              ++

    test_ansi.py:20: AssertionError

**Comment by untitaker** [comment]
@tehmaze Could you take a look at this? If you don't have time to maintain this project, I'd be willing to take it over.

**Comment by jquast** [comment]
I may also assist Mr. Maze! Let us know

**Comment by tehmaze** [comment]
Thanks Markus!

**Pull request merged**
